---
- hosts: all
  name: Install repository
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - ansible.builtin.wait_for_connection:
      delay: 5
      timeout: 600

    - name: Gather facts for first time
      ansible.builtin.setup:

  roles:
    - setup_repo
    - setup_touchstone_tools


- hosts: all
  name: Install PostgreSQL
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        disable_logging: false
        patroni_pg_init_params:
          - name: wal_keep_size
            value: "512MB"
          - name: shared_buffers
            value: "16GB"
        pg_postgres_init_params:
          - name: autovacuum_work_mem
            value: "1GB"
          - name: checkpoint_completion_target
            value: "0.93"
          - name: checkpoint_timeout
            value: "30min"
          - name: cpu_tuple_cost
            value: "0.03"
          - name: effective_cache_size
            value: "80GB"
          - name: effective_io_concurrency
            value: '200'
          - name: maintenance_work_mem
            value: "1GB"
          - name: max_parallel_workers
            value: "32"
          - name: max_wal_size
            value: "200GB"
          - name: max_worker_processes
            value: "32"
          - name: min_wal_size
            value: "1GB"
          - name: random_page_cost
            value: "1.1"
          - name: shared_buffers
            value: "16GB"
          - name: ssl
            value: "on"
          - name: wal_buffers
            value: "64MB"
          - name: wal_compression
            value: "off"
          - name: wal_keep_size
            value: "512MB"
          - name: wal_log_hints
            value: "on"
          - name: wal_receiver_timeout
            value: "5s"

  roles:
    - role: install_dbserver
      when: "'install_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_etcd
      when: "'setup_etcd' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_patroni
      when: "'setup_patroni' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_pgbouncer
      when: "'setup_pgbouncer' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: setup_haproxy
      when: "'setup_haproxy' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: manage_pgbouncer
      when: "'manage_pgbouncer' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"
    - role: manage_dbserver
      when: "'manage_dbserver' in lookup('edb_devops.edb_postgres.supported_roles', wantlist=True)"

  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - zlib-devel
        - nano
        - iproute-tc
