---
- hosts: primary
  name: Install repository
  become: true
  gather_facts: false

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - ansible.builtin.wait_for_connection:
      delay: 5
      timeout: 600

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Initialize the user defined variables
      set_fact:
        enable_edb_repo: false

    - name: Create {{ pg_owner }} OS user
      ansible.builtin.user:
        name: "{{ pg_owner }}"
      when: inventory_hostname not in groups['primary']

    - name: Initialize the user defined variables
      set_fact:
        disable_logging: false

  roles:
    - setup_repo
    - manage_operating_system
    - install_dbserver
    - init_dbserver
    - manage_dbserver
    - setup_dbt3

  tasks:
    - name: Set tablespace permissions on the filesystem
      ansible.builtin.file:
        path: "{{ dbt3tsdir }}"
        state: directory
        owner: "{{ pg_owner }}"
        group: "{{ pg_group }}"
        recurse: yes
      when: tablespaces
