---
- hosts: all
  name: Stop sysstat and dbstat collection
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Include stop_system_stats tasks to stop sysstat data collection
      ansible.builtin.include_role:
        name: manage_touchstone_tools
        tasks_from: stop_system_stats
      vars:
        ts_output_dir: "/tmp/touchstone/sysstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}"

    - name: Include stop_db_stats tasks to stop pgsql stats data collection
      ansible.builtin.include_role:
        name: manage_touchstone_tools
        tasks_from: stop_db_stats
      vars:
        ts_output_dir: "/tmp/touchstone/dbstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}"
      when: "'pgbouncer' in group_names"

    - name: Include process_pidstat tasks
      ansible.builtin.include_role:
        name: manage_touchstone_tools
        tasks_from: process_pidstat
      vars:
        pidstat_txt_file: "/tmp/touchstone/sysstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}/pidstat.txt"

    - name: Include plot_sar_data tasks to plot sar data
      ansible.builtin.include_role:
        name: manage_touchstone_tools
        tasks_from: plot_sar_data
      vars:
        ts_output_dir: "/tmp/touchstone/sysstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}"
        ts_plot_output_dir: "/tmp/touchstone/sysstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}"

    - name: Include plot_pidstat_data tasks to plot pidstat data
      ansible.builtin.include_role:
        name: manage_touchstone_tools
        tasks_from: plot_pidstat_data
      vars:
        pidstat_csv_file: "/tmp/touchstone/sysstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}/pidstat.csv"
        ts_output_dir: "/tmp/touchstone/sysstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}"
        ts_plot_output_dir: "/tmp/touchstone/sysstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}/pidstat_plots"

    - name: Include plot_db_data tasks to plot pgsql data
      ansible.builtin.include_role:
        name: manage_touchstone_tools
        tasks_from: plot_db_data
      vars:
        pg_database: "{{ pgbench_db }}"
        ts_output_dir: "/tmp/touchstone/dbstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}"
        ts_plot_output_dir: "/tmp/touchstone/dbstat_{{ inventory_hostname | regex_replace('[^a-zA-Z0-9_]', '_') }}/pgsql_plots"
      when: "'pgbouncer' in group_names"
