---
- hosts: all
  name: Install repository
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - ansible.builtin.wait_for_connection:
      delay: 5
      timeout: 600

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Initialize the user defined variables
      set_fact:
        enable_edb_repo: false

- hosts: hammerdb_driver
  name: Install HammerDB
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  roles:
    - role: setup_hammerdb

  tasks:
    - name: Load servers.yml
      ansible.builtin.include_vars:
        file: "{{ terraform_project_path }}/servers.yml"
        name: infra

    - name: Configure build.tcl
      ansible.builtin.template:
        dest: /home/{{ hammerdb_user }}/build.tcl
        src: templates/build.tcl.j2
        mode: '0755'
        owner: "{{ hammerdb_user }}"
        group: "{{ hammerdb_user }}"

    - name: Configure run.tcl
      ansible.builtin.template:
        dest: /home/{{ hammerdb_user }}/run.tcl
        src: templates/run.tcl.j2
        mode: '0755'
        owner: "{{ hammerdb_user }}"
        group: "{{ hammerdb_user }}"

    - name: Configure run_seq.tcl
      ansible.builtin.template:
        dest: /home/{{ hammerdb_user }}/run_seq.tcl
        src: templates/run.tcl.j2
        mode: '0755'
        owner: "{{ hammerdb_user }}"
        group: "{{ hammerdb_user }}"

    - name: Install package dos2unix
      ansible.builtin.package:
        name:
          - dos2unix
      become: true