---
- hosts: localhost
  name: Generate Terraform infrastructure file
  tasks:
    - name: Generate files
      ansible.builtin.template:
        src: "{{ template_file }}"
        dest: "{{ dest_file }}"
