---
- hosts: dbt2_driver
  name: Run DBT2
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Load servers.yml
      ansible.builtin.include_vars:
        file: "{{ terraform_project_path }}/servers.yml"
        name: infra

    - name: Load infrastructure.yml
      ansible.builtin.include_vars:
        file: "{{ terraform_project_path }}/../infrastructure.yml"
        name: structure

    # DBT-2 driver bug workaround.
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
        - bind-utils
      become: true

    - name: Get IP address of DBaaS system
      ansible.builtin.command:
        cmd: dig {{ infra.servers.databases.postgres.public_ip }} +short
      register: address

    - name: Make sure DBT2 target data dir does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      become: true
      loop:
        - /tmp/dbt2-data
        - /tmp/dbt2-data.tar.gz

    - name: Display dbt2_connections and ansible_processor_nproc
      ansible.builtin.debug:
        msg:
        - "dbt2_connections: {{ dbt2_connections }}"
        - "ansible_processor_nproc: {{ ansible_processor_nproc }}"

    - name: Calculate drivers per processor
      ansible.builtin.set_fact:
        fpp: "{{ ((dbt2_connections | int) / ansible_processor_nproc) | int  }}"

    - name: Get start time
      include_role:
        name: get-aws-cloudwatch-rds-postgres-stats
        tasks_from: get-start-time.yml

    # Use dbt2_connections as a limit to the number of connections that may be
    # opened, which are opened in units matching the number of processors on
    # the driver system.  Also target a 45 minute (2,700,000 ms) rampup time,
    # which is the expected time needed for a 10,000 warehouse database to warm
    # up.
    - name: Start dbt2-run-workload
      ansible.builtin.command:
        cmd: >-
          dbt2 run
            --comment "RDS for PostgreSQL {{ infra.servers.databases.postgres.instance_type }} | {{ structure.aws.databases.postgres.volume.size_gb }} GB | {{ structure.aws.databases.postgres.volume.type }} | {{ structure.aws.databases.postgres.volume.iops }} IOPS | driver {{ infra.servers.machines["dbt2-driver"].instance_type }}"
            --connections-per-processor={{ fpp }}
            --db-host={{ address.stdout_lines[-1] }}
            --db-port={{ infra.servers.databases.postgres.port }}
            --dbaas
            --districts 1
            --duration={{ dbt2_duration }}
            --stats
            --warehouses={{ dbt2_warehouse }}
            pgsql
            /tmp/dbt2-data
      environment:
        PGHOST: "{{ address.stdout_lines[-1] }}"
      become: true
      become_user: "{{ pg_owner }}"
      changed_when: false
      register: result

    - name: Get end time
      include_role:
        name: get-aws-cloudwatch-rds-postgres-stats
        tasks_from: get-end-time.yml

    - name: Workload execution output
      ansible.builtin.debug:
        var: result

    # Ignore errors because dbt2-generate-report needs better return code logic.
    - name: Generate DBT2 report
      ansible.builtin.command:
        cmd: >-
          dbt2 report --html /tmp/dbt2-data
      become: true
      become_user: "{{ pg_owner }}"
      changed_when: false
      register: result

    - name: Report generation output
      ansible.builtin.debug:
        var: result

    - name: Create data archive on remote
      ansible.builtin.command:
        cmd: tar cvzf /tmp/dbt2-data.tar.gz -C /tmp/dbt2-data/ .

    - name: Fetch DBT2 data files to localhost
      ansible.builtin.fetch:
        src: "/tmp/dbt2-data.tar.gz"
        dest: "{{ results_directory }}/"
        flat: true

    - name: Extract data contents to localhost results directory
      ansible.builtin.shell:
        cmd: |
          tar xzf "{{ results_directory }}/dbt2-data.tar.gz" -C "{{ results_directory }}"
      delegate_to: localhost

    - name: Process metrics
      include_role:
        name: get-aws-cloudwatch-rds-postgres-stats
        tasks_from: process-metrics.yml
